### ISSUE TITLE
More like a question, less like a bug!!

### ISSUE THREAD

**Issue by xDGameStudios** [evicertia/HermaFx#29]
I wanted to know why can't I use multiple regex if?! because I wanted to use different patterns according to a property that is an Enum.. so it can have many values.

**Comment by pruiz** [comment]
Hi,

Not sure I understand your issue, maybe you can provide some more context or a code snippet?

I guess you have some issue combining our regex validation attributes, but not sure about the details. When it comes to validate an input against multiple patterns, you can always combine regex patterns with alternances (regex1|regex2), etc. Maybe that may fit you?

**Comment by xDGameStudios** [comment]
[RegularExpressionIf(pattern1, "ContactType", Operator.EqualTo, Types.Phone)]
[RegularExpressionIf(pattern2, "ContactType", Operator.EqualTo, Types.Mobile)] 
public string PhoneNumber { get; set;}

what I mean is using different patterns according to an Enum value.

**Comment by pruiz** [comment]
Right now this is not a supported scenario, but we are open to pull-reqs.
