### ISSUE TITLE
DataAnnotations: Validations GreaterThan/LesserThan don't work propertly

### ISSUE THREAD

**Issue by nmdiaz** [evicertia/HermaFx#45]
I have trying to use the validations GreaterThan/LesserThan and it seems that are not working propertly. When validation reach "ContingentValidationAttribute", cannot recover the value to compare, get null and throws and exception.

**Comment by pruiz** [comment]
Please try to provide a sample code (or even better a unit test) demonstrating the failure. Otherwise it is hard to take a look at it.

**Comment by dzmitry-lahoda** [comment]
put nullable enable into csproj file. and it will force to fix all such issues once and for all. so not sure it will help with legacy frameworks, but overall should.

**Comment by pruiz** [comment]
@dzmitry-lahoda please, provide a pull-req with a failing test, so we can understand your issue.

**Comment by dzmitry-lahoda** [comment]
sorry for bothering you:) I just tyring to tell you how to level up your coding, its up to you to follow or not:) but thans for sharing good oss. please keep evolving.

**Comment by pruiz** [comment]
@dzmitry-lahoda dont worry, you are not bothering. It is just easier to understand issues when provided with a sample code or failing test, as this way we all speak the same language.

**Comment by dzmitry-lahoda** [comment]
so my langauge is `when nullable enabled and all warnings fixed` this for sure fixes any null references from not and on if any. + it adds +1 to credebility of solution.

**Comment by dzmitry-lahoda** [comment]
you do not need test, you can use type system.

**Comment by pruiz** [comment]
I guess you are referring to "C#8 Nullable reference types". Sorry, but supporting C# 8's new features is not our priority right now. But we are open to pull-reqs (hopefully w/ unit-test).

**Comment by dzmitry-lahoda** [comment]
I see. Than nothing to suggest. Types systems are better than unit tests. And C# can backward compile to old version of .NET:). So I still see you should just to do what compuler does and it will be very ok:)

**Comment by pruiz** [comment]
@dzmitry-lahoda Not sure I understand your point, but probably not worth digging anyway, as I think our way of reasoning is quite far from each other's on this matter: relaying on type system for safety or compiler 'protection', and providing unit-tests are two different things/resources, which you seem to think that overlap (not really). You can relay on null reference safety, and even so have logical issues within your code. Yes, you wont have a null value, but will still have **invalid** values, and things wont work anyway.
