### ISSUE TITLE
data annotations 3.1 and 5.0 core packages

### ISSUE THREAD

**Issue by dzmitry-lahoda** [evicertia/HermaFx#48]

**Comment by pruiz** [comment]
An upgrade in order to support natively netstandard2+ is pending, hopefully it will be done soon (a few weeks).

**Comment by dzmitry-lahoda** [comment]
i do not recommend having netstandard2+ as a solution. standard is dead. at least until .net 6 when may be may be they will release standard 3. but may be i am wrong, but very sceptical. multitargeting still the thing.

**Comment by pruiz** [comment]
We do not yet have a final solution defined, as said, we still need to think and implement native support for netcore/netstandard, while maintaining compatibility with .netfx<5, as we still have stuff running on .netfx/mono.

For HermaFx projects with only basic dependencies on fx, providing a single binary/nuget based on netstandard will probably make things easier. For projects using APIs specific to .netfx/.netcore/etc. multi-targeting may be a better fit. And we may even not provide some sub-components for .netfx or .netcore, if we found them to be of no use on each case.

As said, this is something still to be done, and not really defined. But we need to support different use-cases (at least for our internal usage), so probably this is gonna need some reasoning.

**Comment by pruiz** [comment]
Hi @dzmitry-lahoda I've published initial packages supporting netstandard.

Regards
