### ISSUE TITLE
5.1 core fully nullable support for data annotations

### ISSUE THREAD

**Issue by dzmitry-lahoda** [evicertia/HermaFx#49]

**Comment by pruiz** [comment]
@dzmitry-lahoda may you elaborate a little bit?

**Comment by dzmitry-lahoda** [comment]
put Nullable enabled into csproj file and fix warnings

**Comment by pruiz** [comment]
@dzmitry-lahoda please, provide a pull-req with a failing test, so we can understand your issue.

**Comment by dzmitry-lahoda** [comment]
just enable nullable and do what compilers tells:)

**Comment by pruiz** [comment]
I guess you are referring to "C#8 Nullable reference types". Sorry, but supporting C# 8's new features is not our priority right now. But we are open to pull-reqs (hopefully w/ unit-test).
